# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

# development:
#   secret_key_base: 518a6ea1b6a1d57e3092a7085c1df68f9ba9a5ed3f1e6f10292e1c3dd15cd40a4b5c3797a6faeace5934054e41b87219a10a6de8a4c35072bc6919014ec397a0

# test:
#   secret_key_base: adb3af97dc10098fdce40a36fc3c98306b6abeac00e17172f03d3b245a2a9dfda5712c71273617d529ab8d334e75de8023046c5b1f6cb1b97df544f3407efbca

# # Do not keep production secrets in the unencrypted secrets file.
# # Instead, either read values from the environment.
# # Or, use `bin/rails secrets:setup` to configure encrypted secrets
# # and move the `production:` environment over there.

# production:
#   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


development:
  secret_key_base: <%= Figaro.env.secret_key_base %>

test:
  secret_key_base: <%= Figaro.env.secret_key_base %>

production:
  secret_key_base: <%= Figaro.env.secret_key_base %>

